# Generated by Django 5.0 on 2023-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramapi', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rating', models.IntegerField(max_length=1)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
