# Generated by Django 5.0 on 2023-12-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramapi', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number_rating',
            field=models.IntegerField(),
        ),
    ]
