# Generated by Django 5.0 on 2023-12-07 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramapi', '0004_alter_rating_number_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whiskey', models.CharField(max_length=155)),
                ('country', models.CharField(max_length=155)),
                ('part_of_country', models.CharField(max_length=155)),
                ('age_in_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proof', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mash_bill', models.CharField(max_length=155)),
                ('maturation_details', models.CharField(max_length=300)),
                ('nose', models.CharField(max_length=300)),
                ('palate', models.CharField(max_length=300)),
                ('finish', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=1000)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=300)),
                ('published', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_color', to='dramapi.color')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_rating', to='dramapi.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL)),
                ('whiskey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_type', to='dramapi.type')),
            ],
        ),
    ]
