# Generated by Django 5.0 on 2023-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramapi', '0005_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='tailwind_name',
            field=models.CharField(default='default', max_length=155),
            preserve_default=False,
        ),
    ]
