# Generated by Django 5.0 on 2023-12-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramapi', '0006_color_tailwind_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='age_in_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_color', to='dramapi.color'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='finish',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mash_bill',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='maturation_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='part_of_country',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
